
import React, { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ChevronDown, Eye, KeyRound, Mail, MonitorUp, Play, Settings, Square, UserPen, UserPlus, X } from "lucide-react";
import { createClient } from "@supabase/supabase-js";
import "./style.css";

const supabase = createClient(
  "https://ycyfpuoxuosiuzkfncxq.supabase.co",
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InljeWZwdW94dW9zaXV6a2ZuY3hxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk2Mjk2ODIsImV4cCI6MjA5NTIwNTY4Mn0.WxNlseiNdJwFa4TzpRrRHeSI9pKulfesNwnZpChS-IA"
);

const SUPPORT_EMAIL = "support@aetherai.app";
const logoSrc = "data:image/svg+xml,%3Csvg width='128' height='128' viewBox='0 0 128 128' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M27 25C23 21 16 24 18 30L31 84C33 92 42 95 49 90L78 69C84 65 84 56 78 52L27 25Z' fill='%23B487EA'/%3E%3Crect x='48' y='60' width='34' height='8' rx='4' fill='%235B21B6'/%3E%3Cpath d='M76 74C82 72.5 85.5 69 87 63C88.5 69 92 72.5 98 74C92 75.5 88.5 79 87 85C85.5 79 82 75.5 76 74Z' fill='%237C1DFF'/%3E%3C/svg%3E";

const fallbackModels = [{ id: "openrouter/free", name: "Auto Free Router", description: "Automatically picks an available free model" }];
const speedOptions = [{ name: "Fast", description: "Lowest latency responses" }, { name: "Moderate", description: "Balanced speed and quality" }, { name: "Slow", description: "Best reasoning and accuracy" }];
const languages = [{ code: "en", name: "English" }, { code: "it", name: "Italiano" }, { code: "es", name: "Español" }, { code: "fr", name: "Français" }];

const blockedKeywordsByLanguage = {
  en: ["password","passcode","pin","otp","2fa","verification code","credit card","card number","cvv","bank account","wire transfer","payment","paypal","crypto","wallet","seed phrase","private key","api key","token","secret key","login","sign in","delete file","erase","format disk","factory reset","buy","purchase","checkout"],
  it: ["password","parola d'ordine","codice pin","pin","otp","codice di verifica","codice a due fattori","carta di credito","numero carta","cvv","conto bancario","iban","bonifico","pagamento","paypal","crypto","wallet","frase seed","chiave privata","chiave api","token","login","accesso","elimina file","cancella file","formatta","ripristino di fabbrica","compra","acquista","checkout"],
  es: ["contraseña","clave","pin","otp","código de verificación","código de dos factores","tarjeta de crédito","número de tarjeta","cvv","cuenta bancaria","iban","transferencia bancaria","pago","paypal","cripto","billetera","frase semilla","clave privada","clave api","token","inicio de sesión","eliminar archivo","borrar archivo","formatear","restablecimiento de fábrica","comprar","pagar"],
  fr: ["mot de passe","code pin","pin","otp","code de vérification","code à deux facteurs","carte de crédit","numéro de carte","cvv","compte bancaire","iban","virement bancaire","paiement","paypal","crypto","portefeuille","phrase seed","clé privée","clé api","token","connexion","supprimer fichier","effacer fichier","formater","réinitialisation usine","acheter","paiement"],
};

const text = {
  en: { subtitle:"Safe screen control with confirmation before every action.", account:"Account", createAccount:"Create account", login:"Login", logout:"Logout", authSuccess:"Authentication successful.", verificationSent:"Verification code sent to your email.", verificationPlaceholder:"Enter the 8-digit verification code", verify:"Verify", accountSettings:"Account settings", changeName:"Change username", changeEmail:"Change email", changePassword:"Change password", contactSupport:"Contact support", supportDescription:"Get help from the Aether AI team.", confirmationEmail:"A confirmation email has been sent.", authError:"Authentication failed.", settings:"Settings", sharedScreen:"Shared screen", live:"Live", idle:"Idle", noScreen:"No shared screen", shareScreen:"Share screen", stop:"Stop", prompt:"Prompt", placeholder:"Describe what Aether should do...", model:"Model", speed:"AI Speed", start:"Start", checking:"Checking...", sensitive:"Sensitive request detected.", ready:"Ready to help.", guestModelsLocked:"Login required to unlock all AI models.", guestTimeLimit:"Guest screen sharing is limited to 5 minutes.", writePrompt:"Write a prompt first.", shareFirst:"Share your screen first.", screenActive:"Screen sharing is active.", screenEnded:"Screen sharing ended.", screenStopped:"Screen sharing stopped.", screenDenied:"Screen permission denied or unavailable.", blocked:"Blocked: sensitive or risky request detected.", accountTitle:"Create account", accountSub:"Save your preferences and AI setup.", name:"Choose a username", email:"Enter your email address", password:"No password needed. A secure login code will be sent to your email.", create:"Create", settingsTitle:"Settings", language:"Language", enterNewUsername:"Enter a new username first.", enterNewEmail:"Enter a new email first.", footer:"Made with <3 from the Aether AI Dev" },
  it: { subtitle:"Controllo schermo sicuro con conferma prima di ogni azione.", account:"Account", createAccount:"Crea account", login:"Accedi", logout:"Esci", authSuccess:"Accesso riuscito.", verificationSent:"Codice di verifica inviato via email.", verificationPlaceholder:"Inserisci il codice di verifica a 8 cifre", verify:"Verifica", accountSettings:"Impostazioni account", changeName:"Cambia nome utente", changeEmail:"Cambia email", changePassword:"Cambia password", contactSupport:"Contatta il supporto", supportDescription:"Ricevi aiuto dal team di Aether AI.", confirmationEmail:"Email di conferma inviata.", authError:"Autenticazione fallita.", settings:"Impostazioni", sharedScreen:"Schermo condiviso", live:"Live", idle:"Inattivo", noScreen:"Nessuno schermo condiviso", shareScreen:"Condividi schermo", stop:"Ferma", prompt:"Prompt", placeholder:"Descrivi cosa deve fare Aether...", model:"Modello", speed:"Velocità AI", start:"Avvia", checking:"Controllo...", sensitive:"Richiesta sensibile rilevata.", ready:"Pronto ad aiutarti.", guestModelsLocked:"Accedi per sbloccare tutti i modelli AI.", guestTimeLimit:"La condivisione schermo guest è limitata a 5 minuti.", writePrompt:"Scrivi prima un prompt.", shareFirst:"Condividi prima lo schermo.", screenActive:"Condivisione schermo attiva.", screenEnded:"Condivisione schermo terminata.", screenStopped:"Condivisione schermo fermata.", screenDenied:"Permesso schermo negato o non disponibile.", blocked:"Bloccato: richiesta sensibile o rischiosa rilevata.", accountTitle:"Crea account", accountSub:"Salva preferenze e configurazione AI.", name:"Scegli un nome utente", email:"Inserisci la tua email", password:"Nessuna password necessaria. Riceverai un codice sicuro via email.", create:"Crea", settingsTitle:"Impostazioni", language:"Lingua", enterNewUsername:"Inserisci prima un nuovo nome utente.", enterNewEmail:"Inserisci prima una nuova email.", footer:"Made with <3 from the Aether AI Dev" },
  es: { subtitle:"Control seguro de pantalla con confirmación antes de cada acción.", account:"Cuenta", createAccount:"Crear cuenta", login:"Iniciar sesión", logout:"Salir", authSuccess:"Autenticación correcta.", verificationSent:"Código enviado a tu email.", verificationPlaceholder:"Introduce el código de 8 dígitos", verify:"Verificar", accountSettings:"Ajustes de cuenta", changeName:"Cambiar usuario", changeEmail:"Cambiar email", changePassword:"Cambiar contraseña", contactSupport:"Contactar soporte", supportDescription:"Obtén ayuda del equipo de Aether AI.", confirmationEmail:"Se ha enviado un email de confirmación.", authError:"Autenticación fallida.", settings:"Ajustes", sharedScreen:"Pantalla compartida", live:"En vivo", idle:"Inactivo", noScreen:"No hay pantalla compartida", shareScreen:"Compartir pantalla", stop:"Detener", prompt:"Prompt", placeholder:"Describe qué debe hacer Aether...", model:"Modelo", speed:"Velocidad AI", start:"Iniciar", checking:"Comprobando...", sensitive:"Solicitud sensible detectada.", ready:"Listo para ayudar.", guestModelsLocked:"Inicia sesión para desbloquear todos los modelos AI.", guestTimeLimit:"La pantalla compartida para invitados está limitada a 5 minutos.", writePrompt:"Escribe un prompt primero.", shareFirst:"Comparte tu pantalla primero.", screenActive:"Pantalla compartida activa.", screenEnded:"Pantalla compartida finalizada.", screenStopped:"Pantalla compartida detenida.", screenDenied:"Permiso de pantalla denegado o no disponible.", blocked:"Bloqueado: solicitud sensible o riesgosa detectada.", accountTitle:"Crear cuenta", accountSub:"Guarda tus preferencias y configuración AI.", name:"Elige un nombre de usuario", email:"Introduce tu correo electrónico", password:"No necesitas contraseña. Recibirás un código seguro por email.", create:"Crear", settingsTitle:"Ajustes", language:"Idioma", enterNewUsername:"Introduce un nuevo usuario primero.", enterNewEmail:"Introduce un nuevo email primero.", footer:"Made with <3 from the Aether AI Dev" },
  fr: { subtitle:"Contrôle d'écran sécurisé avec confirmation avant chaque action.", account:"Compte", createAccount:"Créer un compte", login:"Connexion", logout:"Déconnexion", authSuccess:"Authentification réussie.", verificationSent:"Code envoyé par email.", verificationPlaceholder:"Entre le code de vérification à 8 chiffres", verify:"Vérifier", accountSettings:"Paramètres du compte", changeName:"Changer le nom", changeEmail:"Changer l'email", changePassword:"Changer le mot de passe", contactSupport:"Contacter le support", supportDescription:"Obtiens de l'aide de l'équipe Aether AI.", confirmationEmail:"Un email de confirmation a été envoyé.", authError:"Authentification échouée.", settings:"Paramètres", sharedScreen:"Écran partagé", live:"En direct", idle:"Inactif", noScreen:"Aucun écran partagé", shareScreen:"Partager l'écran", stop:"Arrêter", prompt:"Prompt", placeholder:"Décris ce qu'Aether doit faire...", model:"Modèle", speed:"Vitesse AI", start:"Démarrer", checking:"Vérification...", sensitive:"Demande sensible détectée.", ready:"Prêt à aider.", guestModelsLocked:"Connecte-toi pour débloquer tous les modèles AI.", guestTimeLimit:"Le partage d'écran invité est limité à 5 minutes.", writePrompt:"Écris d'abord un prompt.", shareFirst:"Partage d'abord ton écran.", screenActive:"Partage d'écran actif.", screenEnded:"Partage d'écran terminé.", screenStopped:"Partage d'écran arrêté.", screenDenied:"Permission d'écran refusée ou indisponible.", blocked:"Bloqué : demande sensible ou risquée détectée.", accountTitle:"Créer un compte", accountSub:"Enregistre tes préférences et ta configuration AI.", name:"Choisis un nom d'utilisateur", email:"Entre ton adresse email", password:"Aucun mot de passe requis. Un code sécurisé sera envoyé par email.", create:"Créer", settingsTitle:"Paramètres", language:"Langue", enterNewUsername:"Entre d'abord un nouveau nom.", enterNewEmail:"Entre d'abord un nouvel email.", footer:"Made with <3 from the Aether AI Dev" },
};

function normalizePrompt(value){return value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9@._\s-]/gi," ").replace(/\s+/g," ").trim();}
function isPromptBlocked(prompt){const p=normalizePrompt(prompt);return Object.values(blockedKeywordsByLanguage).flat().some(w=>p.includes(normalizePrompt(w)));}
async function askOpenRouterSafetyJudge(prompt, language){try{const r=await fetch("/api/moderate-prompt",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt,language,preferredModel:"google/gemma-3-27b-it:free"})}); if(!r.ok)return false; return Boolean((await r.json()).blocked);}catch{return false;}}
function formatModelDescription(m){return `${m?.context_length?.toLocaleString?.() || "Unknown"} context • ${m?.architecture?.modality || "text"}`;}
function getFreeModels(data){if(!Array.isArray(data))return fallbackModels; const models=data.filter(m=>m.id==="openrouter/free"||m.id?.endsWith(":free")||(Number(m?.pricing?.prompt??1)===0&&Number(m?.pricing?.completion??1)===0)).map(m=>({id:m.id,name:m.name||m.id,description:formatModelDescription(m)})).sort((a,b)=>a.id==="openrouter/free"?-1:b.id==="openrouter/free"?1:a.name.localeCompare(b.name)); return models.length?models:fallbackModels;}

console.assert(isPromptBlocked("enter my password") === true);
console.assert(isPromptBlocked("inserisci il mio codice di verifica") === true);
console.assert(isPromptBlocked("help me click the next button") === false);
console.assert(getFreeModels([{ id: "x/free:free", pricing: { prompt: "0", completion: "0" } }]).length === 1);

function Logo(){return <img src={logoSrc} alt="Aether AI Logo" className="logo" />;}
function Dropdown({label,valueTitle,valueDescription,isOpen,onToggle,children}){return <div className="dropdown-wrap"><span className="label">{label}</span><div className="dropdown"><button type="button" onClick={onToggle} className="dropdown-trigger"><span><strong>{valueTitle}</strong><small>{valueDescription}</small></span><ChevronDown className={isOpen?"chevron open":"chevron"} size={19}/></button><AnimatePresence>{isOpen&&<motion.div initial={{opacity:0,y:8,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:8,scale:.98}} className="dropdown-menu">{children}</motion.div>}</AnimatePresence></div></div>;}
function Modal({children}){return <motion.div className="modal-bg" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div className="modal" initial={{opacity:0,y:16,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:16,scale:.98}}>{children}</motion.div></motion.div>;}
function ModalHeader({title,subtitle,onClose}){return <div className="modal-header"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><button type="button" onClick={onClose} className="icon-btn"><X size={18}/></button></div>;}
function StatusMessage({children,error=false}){return <p className={error?"status error":"status"}>{children}</p>;}

export default function App(){
  const videoRef=useRef(null), guestTimeoutRef=useRef(null);
  const [prompt,setPrompt]=useState(""), [screenActive,setScreenActive]=useState(false), [aiActive,setAiActive]=useState(false);
  const [modelMenuOpen,setModelMenuOpen]=useState(false), [speedMenuOpen,setSpeedMenuOpen]=useState(false), [languageMenuOpen,setLanguageMenuOpen]=useState(false);
  const [availableModels,setAvailableModels]=useState(fallbackModels), [selectedModel,setSelectedModel]=useState(fallbackModels[0]), [selectedSpeed,setSelectedSpeed]=useState(speedOptions[1]);
  const [language,setLanguage]=useState("en"), [user,setUser]=useState(null);
  const [accountOpen,setAccountOpen]=useState(false), [accountSettingsOpen,setAccountSettingsOpen]=useState(false), [settingsOpen,setSettingsOpen]=useState(false);
  const [accountActionOpen,setAccountActionOpen]=useState(false), [accountAction,setAccountAction]=useState(null), [accountActionValue,setAccountActionValue]=useState("");
  const [authMode,setAuthMode]=useState("signup"), [authName,setAuthName]=useState(""), [authEmail,setAuthEmail]=useState(""), [authLoading,setAuthLoading]=useState(false);
  const [verificationStep,setVerificationStep]=useState(false), [verificationCode,setVerificationCode]=useState("");
  const [message,setMessage]=useState("Ready to help."), [safetyChecking,setSafetyChecking]=useState(false);
  const t=text[language], isBlocked=useMemo(()=>isPromptBlocked(prompt),[prompt]);

  useEffect(()=>{supabase.auth.getSession().then(({data})=>setUser(data.session?.user??null)); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null)); return()=>data.subscription.unsubscribe();},[]);
  useEffect(()=>{let cancelled=false; (async()=>{try{const json=await (await fetch("https://openrouter.ai/api/v1/models")).json(); const free=getFreeModels(json.data); const list=user?free:[free[0]||fallbackModels[0]]; if(!cancelled){setAvailableModels(list); setSelectedModel(cur=>list.some(m=>m.id===cur.id)?cur:list[0]);}}catch{if(!cancelled){setAvailableModels(fallbackModels);setSelectedModel(fallbackModels[0]);}}})(); return()=>{cancelled=true};},[user]);

  function clearGuestTimer(){if(guestTimeoutRef.current){clearTimeout(guestTimeoutRef.current);guestTimeoutRef.current=null;}}
  async function startScreenShare(){try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false}); if(videoRef.current)videoRef.current.srcObject=stream; setScreenActive(true); setMessage(user?t.screenActive:`${t.screenActive} ${t.guestTimeLimit}`); if(!user){clearGuestTimer(); guestTimeoutRef.current=setTimeout(()=>{const s=videoRef.current?.srcObject; if(s)s.getTracks().forEach(tr=>tr.stop()); if(videoRef.current)videoRef.current.srcObject=null; setScreenActive(false); setAiActive(false); setMessage(t.guestTimeLimit);},5*60*1000);} stream.getVideoTracks()[0].onended=()=>{clearGuestTimer(); setScreenActive(false); setAiActive(false); setMessage(t.screenEnded);};}catch{setMessage(t.screenDenied);}}
  function stopScreenShare(){const stream=videoRef.current?.srcObject; if(stream)stream.getTracks().forEach(t=>t.stop()); if(videoRef.current)videoRef.current.srcObject=null; clearGuestTimer(); setScreenActive(false); setAiActive(false); setMessage(t.screenStopped);}
  async function sendVerificationEmail(email){const result=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:authMode==="signup",emailRedirectTo:window.location.origin,data:authMode==="signup"?{name:authName}:undefined}}); if(result.error)throw result.error;}
  async function handleAuthSubmit(){setAuthLoading(true); if(!verificationStep){try{await sendVerificationEmail(authEmail); setVerificationStep(true); setMessage(t.verificationSent);}catch(e){setMessage(`${t.authError} ${e.message||""}`.trim());}finally{setAuthLoading(false);} return;} try{const result=await supabase.auth.verifyOtp({email:authEmail,token:verificationCode,type:"email"}); if(result.error)throw result.error; setMessage(t.authSuccess); setAccountOpen(false); setAuthName(""); setAuthEmail(""); setVerificationCode(""); setVerificationStep(false);}catch(e){setMessage(`${t.authError} ${e.message||""}`.trim());}finally{setAuthLoading(false);}}
  async function handleLogout(){await supabase.auth.signOut(); setUser(null); setAccountSettingsOpen(false); setMessage(t.ready);}
  function openAccountAction(action){setAccountAction(action); setAccountActionValue(""); setAccountActionOpen(true);}
  async function handleAccountAction(){if(!user||!accountAction)return; try{if(accountAction==="name"){if(!accountActionValue.trim()){setMessage(t.enterNewUsername);return;} const r=await supabase.auth.updateUser({data:{name:accountActionValue.trim()}}); if(r.error)throw r.error;} if(accountAction==="email"){if(!accountActionValue.trim()){setMessage(t.enterNewEmail);return;} const r=await supabase.auth.updateUser({email:accountActionValue.trim()}); if(r.error)throw r.error;} if(accountAction==="password"){const r=await supabase.auth.resetPasswordForEmail(user.email,{redirectTo:window.location.origin}); if(r.error)throw r.error;} setMessage(t.confirmationEmail); setAccountActionOpen(false); setAccountActionValue(""); setAccountAction(null);}catch(e){setMessage(`${t.authError} ${e.message||""}`.trim());}}
  async function startAI(){if(!prompt.trim()){setMessage(t.writePrompt);return;} if(!screenActive){setMessage(t.shareFirst);return;} if(isBlocked){setAiActive(false);setMessage(t.blocked);return;} setSafetyChecking(true); const blocked=await askOpenRouterSafetyJudge(prompt,language); setSafetyChecking(false); if(blocked){setAiActive(false);setMessage(t.blocked);return;} if(!user&&selectedModel.id!=="openrouter/free"){setMessage(t.guestModelsLocked);return;} setAiActive(true); setMessage(`Aether AI started with ${selectedModel.name} in ${selectedSpeed.name.toLowerCase()} mode.`);}
  function authMessageLooksLikeError(){const lower=message.toLowerCase(); return ["failed","fallita","échouée","fallida","invalid","expired"].some(w=>lower.includes(w));}

  return <main className="app"><div className="container">
    <header className="header card"><div className="brand"><Logo/><div><h1>Aether AI</h1><p>{t.subtitle}</p></div></div><div className="header-actions">{user&&<button className="circle-btn" onClick={()=>setAccountSettingsOpen(true)}><UserPen size={17}/></button>}{!user&&<button className="pill-btn secondary" onClick={()=>setAccountOpen(true)}><UserPlus size={17}/>{t.account}</button>}<button className="circle-btn" onClick={()=>setSettingsOpen(true)}><Settings size={17}/></button></div></header>
    <section className="main-grid">
      <div className="card panel"><div className="panel-top"><div className="panel-title"><MonitorUp size={18}/>{t.sharedScreen}</div><span className={screenActive?"badge live":"badge"}>{screenActive?t.live:t.idle}</span></div><div className="screen-box"><video ref={videoRef} autoPlay muted />{!screenActive&&<div className="empty-screen"><div className="empty-icon"><Eye size={38}/></div><p>{t.noScreen}</p></div>}</div><div className="button-row"><button className="pill-btn" onClick={startScreenShare}><MonitorUp size={17}/>{t.shareScreen}</button><button className="pill-btn secondary" onClick={stopScreenShare}><Square size={17}/>{t.stop}</button></div></div>
      <div className="card panel"><label className="field"><span className="label">{t.prompt}</span><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={t.placeholder}/></label>{!user&&<div className="guest-warning">{t.guestModelsLocked}</div>}
      <Dropdown label={`${t.model} • ${availableModels.length}`} valueTitle={selectedModel.name} valueDescription={selectedModel.description} isOpen={modelMenuOpen} onToggle={()=>{setModelMenuOpen(v=>!v);setSpeedMenuOpen(false);}}>{availableModels.map(model=><button key={model.id} type="button" className="dropdown-option" onClick={()=>{setSelectedModel(model);setModelMenuOpen(false);}}><strong>{model.name}</strong><small>{model.description}</small></button>)}</Dropdown>
      <Dropdown label={t.speed} valueTitle={selectedSpeed.name} valueDescription={selectedSpeed.description} isOpen={speedMenuOpen} onToggle={()=>{setSpeedMenuOpen(v=>!v);setModelMenuOpen(false);}}>{speedOptions.map(speed=><button key={speed.name} type="button" className="dropdown-option" onClick={()=>{setSelectedSpeed(speed);setSpeedMenuOpen(false);}}><strong>{speed.name}</strong><small>{speed.description}</small></button>)}</Dropdown>
      <button className="pill-btn full" onClick={startAI} disabled={isBlocked||safetyChecking}><Play size={18}/>{safetyChecking?t.checking:t.start}</button><StatusMessage error={isBlocked}>{isBlocked?t.sensitive:message}</StatusMessage></div>
    </section>
    <footer>{t.footer}</footer>

    <AnimatePresence>{accountOpen&&<Modal><ModalHeader title={authMode==="signup"?t.accountTitle:t.login} subtitle={t.accountSub} onClose={()=>setAccountOpen(false)}/><div className="form-stack"><div className="tabs"><button type="button" onClick={()=>{setAuthMode("signup");setVerificationStep(false);}} className={authMode==="signup"?"active":""}>{t.createAccount}</button><button type="button" onClick={()=>{setAuthMode("login");setVerificationStep(false);}} className={authMode==="login"?"active":""}>{t.login}</button></div>{authMode==="signup"&&<input value={authName} onChange={e=>setAuthName(e.target.value)} placeholder={t.name}/>}<input value={authEmail} onChange={e=>setAuthEmail(e.target.value)} placeholder={t.email} type="email"/><p className="small-help">{t.password}</p>{verificationStep&&<input value={verificationCode} onChange={e=>setVerificationCode(e.target.value)} placeholder={t.verificationPlaceholder}/>}<button className="pill-btn full" onClick={handleAuthSubmit} disabled={authLoading||!authEmail||(verificationStep&&verificationCode.length!==8)}>{authLoading?"...":authMode==="signup"?t.create:t.login}</button>{message&&<StatusMessage error={authMessageLooksLikeError()}>{message}</StatusMessage>}</div></Modal>}</AnimatePresence>

    <AnimatePresence>{accountSettingsOpen&&<Modal><ModalHeader title={t.accountSettings} subtitle={user?.email} onClose={()=>setAccountSettingsOpen(false)}/><div className="form-stack"><button className="settings-row" onClick={()=>openAccountAction("name")}><UserPen size={18}/>{t.changeName}</button><button className="settings-row" onClick={()=>openAccountAction("email")}><Mail size={18}/>{t.changeEmail}</button><button className="settings-row" onClick={()=>openAccountAction("password")}><KeyRound size={18}/>{t.changePassword}</button><button className="settings-row" onClick={()=>window.location.href=`mailto:${SUPPORT_EMAIL}`}><Mail size={18}/><span>{t.contactSupport}<small>{t.supportDescription}</small></span></button><button className="settings-row danger" onClick={handleLogout}><Square size={18}/>{t.logout}</button></div></Modal>}</AnimatePresence>

    <AnimatePresence>{settingsOpen&&<Modal><ModalHeader title={t.settingsTitle} subtitle={t.language} onClose={()=>setSettingsOpen(false)}/><Dropdown label={t.language} valueTitle={languages.find(i=>i.code===language)?.name||"English"} valueDescription={t.settings} isOpen={languageMenuOpen} onToggle={()=>setLanguageMenuOpen(v=>!v)}>{languages.map(item=><button key={item.code} type="button" className="dropdown-option" onClick={()=>{setLanguage(item.code);setMessage(text[item.code].ready);setLanguageMenuOpen(false);}}><strong>{item.name}</strong></button>)}</Dropdown></Modal>}</AnimatePresence>

    <AnimatePresence>{accountActionOpen&&<Modal><ModalHeader title={accountAction==="name"?t.changeName:accountAction==="email"?t.changeEmail:t.changePassword} subtitle={t.confirmationEmail} onClose={()=>setAccountActionOpen(false)}/><div className="form-stack">{accountAction!=="password"&&<input value={accountActionValue} onChange={e=>setAccountActionValue(e.target.value)} placeholder={accountAction==="name"?t.name:t.email} type={accountAction==="email"?"email":"text"}/>}<button className="pill-btn full" onClick={handleAccountAction}>{accountAction==="password"?t.confirmationEmail:t.verify}</button></div></Modal>}</AnimatePresence>
  </div></main>;
}
